#!/bin/bash

# Bootstraps server

# Add shortcuts
echo "alias jkl='sudo su -'" >> /etc/profile
ln -s /var/lib/cloud/instance/scripts/part-001 /root/user_data

# Make sure git and node are installed
yum -y install git nodejs npm --enablerepo=epel

# Clone repo and/or checkout code
cd /opt
if [ ! -d "greetings_src" ]; then
    git clone https://github.com/maplebird/greetings_src.git
fi
cd greetings_src
git checkout master
git pull

# Install init.d service
/bin/cp -f greetings_src/sys/greetings /etc/rc.d/init.d/
chmod +x /etc/rc.d/init.d/greetings

# Clean, install dependencies
service greetings stop
cd greetings_src
rm -rf node_modules
npm install

# Start the API
service greetings start

# Show service status
service greetings status